2024-05-08 11:53:38,946 [ERROR] in django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/Users/My PC/PycharmProjects/ThisIsMyProject/mysite/myapp/views.py", line 214, in get
    name = elem['naem']
KeyError: 'naem'
